#! /bin/bash
source ~/src/choptitle/common.sh

TARGETPATH="/var/tmp/findscreen"

while read line; do
	file=$(echo "$line" | cut -d':' -f1)
	timestamp=$(echo "$line" | cut -d':' -f3)
	filename=$(basename -z -s .mkv $(basename -z "$file"))
	#mplayer -noconsolecontrols -vo "jpeg:outdir=$TARGETPATH" -frames 1 -ss $timestamp "$file" > /dev/null 2>&1
	#if [ -f "$TARGETPATH/00000001.jpg" ]; then
	#	mv -v "$TARGETPATH/00000001.jpg" "$TARGETPATH"/$(basename -z -s .mkv $(basename -z "$file")).jpg
	#else
	#	echo "findscreen: mplayer failed to capture screen"
	#	continue
	#fi
	echo $filename
	ffmpeg -i "$file" -an -ss $timestamp -y -vframes 1 $TARGETPATH/$filename.jpg > /dev/null 2>&1
done
